# Generated by Django 5.2.4 on 2025-07-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Date Modified"),
        ),
    ]
