# Generated by Django 5.2.4 on 2025-07-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="static/DEFAULT_PROFILE_PICTURE.png",
                upload_to="profile/user_avatar/",
            ),
        ),
    ]
