# Generated by Django 5.2.4 on 2025-07-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(upload_to="profile/user_avatar/"),
        ),
    ]
